apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-2025-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: backend.devops-2025
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: devops-2025-backend
                port:
                  number: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: devops-2025-backend
spec:
  selector:
    app: devops-2025-backend
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-2025-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-2025-backend
  template:
    metadata:
      labels:
        app: devops-2025-backend
    spec:
      containers:
        - name: devops-2025-backend
          image: leon2281337/devops_lab1-backend:amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres_password
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m